### ISSUE TITLE
ModuleNotFoundError: No module named 'openai'

### ISSUE THREAD

**Issue by ghost** [Hexanol777/GLadOS-Voice-Assistant#1]
Traceback (most recent call last):
  File "/home/cave/GLadOS-Voice-Assistant/GLadOS.py", line 2, in <module>
    import openai
ModuleNotFoundError: No module named 'openai'

What the fuck is going on?

**Comment by Hexanol777** [comment]
Looks like you're missing the 'openai' module. Try installing it using the below command in your terminal:

```bash
pip install openai
```
Also make sure to replace the `"OAI_key": "YOUR-API-KEY-HERE"` in the `config.json` file with your own OpenAI API key.

**Comment by ghost** [comment]
thanks for the advice, but... the thing is... i already did that

**Comment by ghost** [comment]
![Screenshot 2024-01-20 105143](https://github.com/Hexanol777/GLadOS-Voice-Assistant/assets/105581753/b5ffc01e-ae70-45e5-a34b-80e46f3adc94) now it's giving me this

**Comment by Hexanol777** [comment]
Seems like OpenAI has decided to deprecate the `text-davinci-003` model, change it to `gpt-3.5-turbo-instruct` in the `config.json` file and let me know if you still encounter an error.
![image](https://github.com/Hexanol777/GLadOS-Voice-Assistant/assets/52779550/0bfd9057-6a4c-4c0b-ace9-e4a05501e8bc)

**Comment by ghost** [comment]
Thank you so much, it works now!

**Comment by ghost** [comment]
![immagine](https://github.com/Hexanol777/GLadOS-Voice-Assistant/assets/105581753/64e808f8-9ba2-4a95-abba-48733582454a)
Can you make it actually release neurotoxin through the pc's exhaust vents? (joke)

**Comment by ghost** [comment]
![immagine](https://github.com/Hexanol777/GLadOS-Voice-Assistant/assets/105581753/26c71f84-1eb7-4031-ae98-a9249baa9657)
Wait a minute... i can't do more than one prompt, i need to restart it for every prompt

**Comment by Hexanol777** [comment]
> Thank you so much, it works now!

Glad i could help you out.

> ![immagine](https://private-user-images.githubusercontent.com/105581753/298275378-26c71f84-1eb7-4031-ae98-a9249baa9657.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU3NDU0MzQsIm5iZiI6MTcwNTc0NTEzNCwicGF0aCI6Ii8xMDU1ODE3NTMvMjk4Mjc1Mzc4LTI2YzcxZjg0LTFlYjctNDAzMS1hZTk4LWE5MjQ5YmFhOTY1Ny5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTIwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDEyMFQxMDA1MzRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03Mjc5YTc3NTc1OTAxYTk2NmVlNjc0MWRhMzhlOTU3NGY4Y2JiYTk3MjhiMzgzNDYzMTExOTM0NzI4NWQwMDQzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.tleSgJVlU9zLm2pb__j5YUfhd0BUbj5F4NpagcZaqfA) Wait a minute... i can't do more than one prompt, i need to restart it for every prompt
```python
        # Play audio file
        if 'winsound' in mod:
            winsound.PlaySound(output_file, winsound.SND_FILENAME)
        else:
            try:
                call(["aplay", "./output.wav"])
            except FileNotFoundError:
                call(["pw-play", "./output.wav"])
```
The issue arises from this block of code, i believe it has something to do with the fact that i designed this on windows while not doing much testing on Linux and just including a try except case for it, i think updating the aplay, pipewire, eSpeak could help. 
```bash
sudo apt install -y espeak
sudo apt install pipewire
sudo apt-get install -y alsa-utils
```
someone in a stackoverflow thread seem to have fixed this issue by replacing `/` with `\\`. not much of a solution but give it a shot.









> ![immagine](https://private-user-images.githubusercontent.com/105581753/298275321-64e808f8-9ba2-4a95-abba-48733582454a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU3NDUzMzcsIm5iZiI6MTcwNTc0NTAzNywicGF0aCI6Ii8xMDU1ODE3NTMvMjk4Mjc1MzIxLTY0ZTgwOGY4LTliYTItNGE5NS1hYmJhLTQ4NzMzNTgyNDU0YS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTIwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDEyMFQxMDAzNTdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05MTliNTRjODk2MzFhODMzNGMwMGQ2NjRjNGYwM2Q0NTI2NTQ1OWU5OGFjNWZhOWJlMzg5NWM3N2M5YmM3YTVhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.G48VVAhoi-rHXeln_1EW-v0_CrJ_0gJr9_P8UGG0NuQ) Can you make it actually release neurotoxin through the pc's exhaust vents? (joke)

lol there is a [blog](https://www.henrirantanen.fi/2022/02/10/glados-voice-assistant-with-custom-text-to-speech/?utm_source=github.com&utm_medium=social&utm_campaign=post&utm_content=DIY+GLaDOS+Voice+Assistant+with+Python+and+Raspberry+Pi) on how to turn it into an actual home assistant if you are into that xD
